version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - TASK_TYPE=web
      - AWS_REGION=us-east-1
      - RAILS_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - TASK_TYPE=worker
      - RAILS_ENV=development
    volumes:
      - .:/app